### ISSUE TITLE
Wish: Adding battery "tryk" as a device

### ISSUE THREAD

**Issue by hemandk** [dingusdk/haihc-betatest#4]
Would it be possible that battery "tryk" could be added directly as a device in the integration?

Right now I'm configuring each "tryk" as a binary sensor, so I can use them to control Ikea bulbs or my blinds, but would be nice to have it as a device.

Anyway excellent job on the integration, I really appreciate it alot.

**Comment by dingusdk** [comment]
You can customize the auto setup - [see here](https://www.dingus.dk/customizing-home-assistent-ihc-auto-setup/)
Adding all your battery buttons could be a lot depending on your installation. I would not do it this way unless you only have a few and you actually use them in HA. 
Note you can easially add them individually as binarry sensors using my [ihc viewer](https://github.com/dingusdk/haihcviewer)

**Comment by hemandk** [comment]
> You can customize the auto setup - [see here](https://www.dingus.dk/customizing-home-assistent-ihc-auto-setup/) Adding all your battery buttons could be a lot depending on your installation. I would not do it this way unless you only have a few and you actually use them in HA. Note you can easially add them individually as binarry sensors using my [ihc viewer](https://github.com/dingusdk/haihcviewer)

Thanks I will look into that. I have a mix of using part of it in HA and some in IHC so perhaps it is easier to just add them as binary sensors and use your IHC viewer. 

I made a blueprint for a on/off/dim using two binary sensors and that works pretty well.
